from is_multiple_of_x import is_multiple_of_x
from is_even import is_even
from generate_fibonacci import generate_fibonacci
from generate_even_fibonacci import generate_even_fibonacci
from is_prime import is_prime
